[general]
import = ["./themes/ayu-dark.toml"]

[font]
size = 12.0

[font.bold]
family = "CaskaydiaMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font Propo"
style = "Regular"
